# Automatically generated by configure - do not modify
SRC_PATH=/home/rich/Desktop/pyrebox_upgrade/qemu/roms/vgabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
